// Gene-ID -> gene-symbol lookup for the ID <-> symbol display toggle. Supports
// human (Ensembl ENSG…) and Drosophila melanogaster (FlyBase FBgn…). Each map
// is an EXTERNAL, user-editable `.tsv.gz` file in a `gene_maps/` folder next to
// the app (generated by scripts/fetch-gene-symbols.ps1 from Ensembl BioMart);
// it is NOT embedded in the executable. The Rust `read_gene_map` command reads
// the file and the frontend decompresses it lazily on first use. When the
// folder/file is absent the toggle degrades to showing raw gene IDs.
// Display-only: it never changes the underlying gene_id used for identity.

import { isTauriContext, readGeneMap, readGeneMapFile } from "./tauri";

export type GeneNameMode = "ensembl" | "symbol";

/** Species whose symbol map we ship. Detected from the gene_id prefix. */
export type Species = "human" | "fly";

// Maps are cached by a source key: the species name for a bundled map, or
// `custom:<path>` for a user-supplied file.
const caches = new Map<string, Map<string, string>>();
const inflight = new Map<string, Promise<Map<string, string>>>();

/** Drop an Ensembl/FlyBase version suffix (`ENSG…​.7` / `FBgn….1` -> base id). */
export function stripVersion(id: string): string {
  const dot = id.indexOf(".");
  return dot >= 0 ? id.slice(0, dot) : id;
}

/**
 * Guess the species from the gene_id format so the right symbol map is loaded:
 * `ENSG…` -> human, `FBgn…` -> Drosophila. Returns null when no row carries a
 * recognised prefix (e.g. the ids are already symbols), in which case the
 * symbol toggle is a no-op.
 */
export function detectSpecies(geneIds: Iterable<string>): Species | null {
  for (const raw of geneIds) {
    const id = stripVersion(raw).toUpperCase();
    if (id.startsWith("FBGN")) return "fly";
    if (id.startsWith("ENSG")) return "human";
  }
  return null;
}

/** Parse gzip-or-plain TSV bytes (`gene_id<TAB>symbol` per line) into a map. */
async function parseGeneMap(buf: Uint8Array<ArrayBuffer>): Promise<Map<string, string>> {
  const m = new Map<string, string>();
  // gzip magic 1f 8b → decompress; otherwise treat as plain TSV.
  let text: string;
  if (buf.length > 2 && buf[0] === 0x1f && buf[1] === 0x8b && typeof DecompressionStream !== "undefined") {
    const stream = new Blob([buf]).stream().pipeThrough(new DecompressionStream("gzip"));
    text = await new Response(stream).text();
  } else {
    text = new TextDecoder().decode(buf);
  }
  for (const line of text.split("\n")) {
    if (!line) continue;
    const tab = line.indexOf("\t");
    if (tab < 0) continue;
    const id = line.slice(0, tab);
    const sym = line.slice(tab + 1).trim();
    if (id && sym) m.set(id, sym);
  }
  return m;
}

/**
 * Load (and cache by `key`) a gene-ID -> symbol map from `getBytes`. Outside the
 * Tauri runtime (browser-only dev) or when the source is missing, degrade to an
 * empty map → symbols fall back to raw IDs instead of throwing.
 */
async function loadCached(
  key: string,
  getBytes: () => Promise<ArrayBuffer>,
): Promise<Map<string, string>> {
  const cached = caches.get(key);
  if (cached) return cached;
  const pending = inflight.get(key);
  if (pending) return pending;
  const p = (async () => {
    if (!isTauriContext()) {
      const empty = new Map<string, string>();
      caches.set(key, empty);
      return empty;
    }
    let m: Map<string, string>;
    try {
      m = await parseGeneMap(new Uint8Array(await getBytes()));
    } catch (e) {
      console.warn(`gene symbol map (${key}) unavailable:`, e);
      m = new Map<string, string>();
    }
    caches.set(key, m);
    return m;
  })();
  inflight.set(key, p);
  try {
    return await p;
  } finally {
    inflight.delete(key);
  }
}

/** Load (and cache, per species) the bundled gene-ID -> symbol map. */
export function loadGeneSymbols(species: Species): Promise<Map<string, string>> {
  return loadCached(species, () => readGeneMap(species));
}

/** Load (and cache, per path) a user-supplied "Custom" gene-ID -> symbol map. */
export function loadCustomGeneMap(path: string): Promise<Map<string, string>> {
  return loadCached(`custom:${path}`, () => readGeneMapFile(path));
}

/** Back-compat alias for the human map. */
export function loadHumanGeneSymbols(): Promise<Map<string, string>> {
  return loadGeneSymbols("human");
}

/**
 * Display name for a gene id under the current mode. In symbol mode, resolve
 * via the map (trying the versioned id then the version-stripped id); fall back
 * to the raw id when not in symbol mode, the map is absent, or no symbol maps.
 */
export function geneDisplayName(
  id: string,
  map: Map<string, string> | null,
  mode: GeneNameMode,
): string {
  if (mode !== "symbol" || !map) return id;
  return map.get(id) ?? map.get(stripVersion(id)) ?? id;
}
